### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by spotlesscoder** [linuxserver/docker-nginx-armhf#13]
I want to be able to build on the code in order to be able to build a new version myself as soon as a new version of nginx is published

**Comment by thelamer** [comment]
Go ahead and build on it, these are wrappers to put applications inside of Docker not applications themselves. 

You will have to do the legwork though to gather up all the licenses of all the packages and technology used in this image if you are planning on using it for something commercial.

**Comment by sparklyballs** [comment]
you're more than welcome to fork as @thelamer said

**Comment by spotlesscoder** [comment]
Ok, Thanks a lot already
